### ISSUE TITLE
 sol_inform['value'] = r["sol_flag"]    #ifail[0] TypeError: tuple indices must be integers, not str

### ISSUE THREAD

**Issue by rgiessmann** [syarra/pyOpt-pyIPOPT#2]
Hi, 

first of all: thanks for your effort! Works like a charm, and even the setup is easier now than described in your Readme, as an option for your package was integrated by the pyOpt team!

When executing the provided example (thanks!!), I get the following error, though:

```
Traceback (most recent call last):
  File "pyOpt-pyIPOPT/IPOPTtest.py", line 93, in <module>
    ipopt(opt_prob,sens_type='FD',store_hst=True)
  File "/home/rgiessmann/anaconda2/lib/python2.7/site-packages/pyOpt/pyOpt_optimizer.py", line 160, in __call__
    return self.__solve__(opt_problem, *args, **kwargs)
  File "/home/rgiessmann/anaconda2/lib/python2.7/site-packages/pyOpt/pyIPOPT/pyIPOPT.py", line 741, in __solve__
    sol_inform['value'] = r["sol_flag"]    #ifail[0]
TypeError: tuple indices must be integers, not str
```

Apart from that, the file seems to execute fine and fins an optimal solution:

```
EXIT: Optimal Solution Found.
```

-- the error appears right after that. 

I didn't have the chance to go into detail about what's happening, do you have any idea?

Thanks in advance,
   Robert

**Comment by syarra** [comment]
Hi Robert,

I fixed the issue in 9243088d53e81942248acaa46cf5891205197839.
The problem was that pyipopt used to return a `dictionnary` but now returns a `tuple`.
